version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app/static/img/produtos:/app/app/static/img/produtos
      - ./app/controllers/db:/app/app/controllers/db
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

